# Generated by Django 2.0.3 on 2018-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='update_date',
            new_name='date_updated',
        ),
    ]
