# Generated by Django 2.0.3 on 2018-04-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_lists', '0002_auto_20180330_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='item_name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='purchase_price(KES')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='item_quantity')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='project_lists.ShoppingList'),
        ),
    ]
