# Generated by Django 2.2.3 on 2019-07-29 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_lists', '0003_auto_20180401_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='activity_name')),
                ('optimist', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pessimist', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ProjectList',
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
        migrations.AddField(
            model_name='activity',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='project_lists.ProjectList'),
        ),
    ]
