# Generated by Django 2.2.3 on 2019-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lists', '0004_auto_20190729_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='estimate_mtv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='estimate_mtvm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='estimate_pcu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
